### ISSUE TITLE
Cannot send hex data when data is 0

### ISSUE THREAD

**Issue by czqinyes** [emqtt/qmqtt#164] opened 2018-12-29 08:39 UTC
When I sent hex data, 
eg: 88 77 66 55 00 11 22 33, only received: 88 77 66 55 
0 and later data will not be sent (00 11 22 33)
I wonder if something wrong, please check and help, thanks

**Comment by ejvr** [comment] 2018-12-29 14:50
My guess is that the problem is in the construction of the `QByteArray` passed to the `QMQTT::Message` constructor. If you use `QByteArray::QByteArray(const char *data, int size = -1) ` and use the default value for the `size` parameter, the constructed `QByteArray` will contain the data up to the for 0 value. Passing the correct side should work as expected.

If this does not fix your problem, please post the code where you create the `QMQTT::Message` and the QT version you are using.

I tested this with the qmqtt example project: qmqtt itself seems to handle 0 values properly.

**Comment by czqinyes** [comment] 2018-12-30 02:01
First, thank you very much for your help.
The problem is I use the "char buf[]" but not the "QByteArray"  passed to the QMQTT::Message constructor.

**Comment by ejvr** [comment] 2018-12-30 07:35
The `char buf[]` will be implicitly converted to a `QByteArray` before the `QMQTT::Message` constructor is called. This will use the same `QByteArray` constructor. In your case I would explicitly create a `QByteArray` from the char array and pass the length of the array. Like this:
```
char buf[] = "abc\0def";
QByteArray bytes(buf, 7);
QMQTT::Message msg(id, topic, bytes);
```

In general: if you pass a char array or char pointer to a function without passing the length, it will be handled as a 0 terminated string. This is not what you want if you pass binary data.

**Comment by mwallnoefer** [comment] 2019-01-02 11:48
Thanks for the correct explanation @ejvr.

I close this since it is not a bug.

**Closed by mwallnoefer** 2019-01-02 11:48 UTC
