### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by TomaszKn** [emqtt/qmqtt#83] opened 2016-10-02 13:24 UTC
HI
I try run QMQTT. 
My code:
`  
     this->client = new QMQTT::Client("192.168.10.93", 8883, true, true);   //SSL

```
 this->client->setClientId(QString(QUuid::createUuid().toString()));

 this->client->setUsername("*****");

 this->client->setPassword("*****");

 //this->client->connect();

 this->client->connectToHost();
```

`
Or I try:
`  
    client = new QMQTT::Client("192.168.10.93", 8883, true, true); //SSL

```
client->setClientId("Piec");

client->setUsername("****");

client->setPassword("*****");

client->setHostName("192.168.10.93");

client->connectToHost();
```

`

But I get always the same error when I run my app.

> Bus error

Any suggestions?

**Comment by mwallnoefer** [comment] 2016-10-05 07:24
@cncap You have contributed to the SSL part of the library. Any ideas why this does not work?

I am not a SSL specialist so I have no clue.

**Comment by mwallnoefer** [comment] 2016-10-26 07:39
Maybe try to revert this commit https://github.com/emqtt/qmqtt/commit/c8ba2f48fd4b4956370c4d6164c0ecf19dfbb7e3, it could be that the counterpart does not support TLSv1.2 yet.

**Comment by mwallnoefer** [comment] 2016-10-26 08:06
A fix attempt: https://github.com/emqtt/qmqtt/commit/5b53ed4447b4c5006685d6b6b27bc1171f41790e

**Comment by ejvr** [comment] 2017-01-05 19:19
I have also worked with MQTT+SSL and I have not seen any SSL specific crashes. The SSL specific code in QMQTT (SslNetwork) is hardly different from the Network class, so it seem unlikely that the problem is located in that part of the code. 
@TomaszKn I would be nice to have a stack trace the the bus error.
My guess is that the problem lies without the (no SSL specific) handling of incomming MQTT frames. I've had some problems there before.

**Comment by mwallnoefer** [comment] 2017-02-10 08:09
@TomaszKn I am closing this now, please reopen if you provide us more information.

**Closed by mwallnoefer** 2017-02-10 08:09 UTC
